wecode-bootcamp-korea/41-1st-Dwae-Getarian-frontend

- src/pages/Main/Components/payment/Payment.jsx
- src/pages/Main/Components/payment/payment.scss
> [41기 권나현]ADD: payment box 레이아웃 추가

- src/Router.js
- src/pages/Main/Components/Footer/Footer.jsx
- src/pages/Main/Components/Footer/Footer.scss
> [41기 조윤환]ADD:footer레이아웃

- src/pages/Main/Components/payment/Payment.jsx
- src/pages/Main/Components/payment/payment.scss
> [41기 권나현]매개변수를 받아와서 cart item 총 합계 구현

- src/pages/Main/Components/Recipe/ImageSlider.js
- src/pages/Main/Components/Recipe/Recipe.jsx
- src/pages/Main/Components/Recipe/Recipe.scss
- src/pages/Main/Components/Recipe/RecipePresent.jsx
- src/pages/Main/Components/Recipe/RecipePresent.scss
- src/pages/Main/Components/Recipe/RecipeTeaWear.jsx
<br />
- 레시피 페이지 부담없는 선물 섹션 페이지네이션 구현 
<br />
- useSearchParams로 offset값 limit값 을 가져와 저장 후 searchParams.toString() 으로 fetch url 설정함.
- 버튼 클릭시 offset 값 변경하는 함수를 구현해 onClick 이벤트로 넣어주었다.
<br />
- 처음에 offset과 limit키의 값을 fetch url에 사용했었는데 null값이 전달돼서 실패 했었지만 searchParams.toString()으로 설정해서 null값 전달을 하지 않아서 페이지네이션을 구현할 수 있었다. 
<br />
> [41기 김진우] 레시피 페이지 페이지네이션 구현

- src/components/Footer/Footer.jsx
-로그인 버튼 클릭시 경로 오류로 인해서 새로 경로 설정
> [41기 조윤환]modify:링크 경로 수정

- src/pages/MySubPage/Benefits/Benefits.scss
<br />
- mypage/beneifts nav 위치 수정
<br />
- mypage/beneifts nav 위치 수정
> [41기 정다경] MODIFY : Benefits.scss 수정

- src/pages/Login/My/ActivityList/ActivityList.scss
<br />
- modifyActivityList.scss 수정
<br />
- modifyActivityList.scss 수정
> [41기 정다경] modifyActivityList.scss 수정

- src/Router.js
<br />
- login, signup 페이지 nav 수정
<br />
- login, signup 페이지 nav 수정
> [41기 정다경] MODIFY : router 수정

- src/Router.js
> [41기 정다경] feature/modifyRouter1 router 수정

- src/components/Best/Best.jsx
- src/components/Best/BestProduct.jsx
- src/components/Nav/Nav.jsx
- src/pages/Login/Login.jsx
- src/pages/Main/Components/Cart/Cart.jsx
- src/pages/Main/Components/Maincomponents/Mainbest/BestItem.jsx
- src/pages/Main/Components/Maincomponents/Mainbest/BestMenu.jsx
- src/pages/Main/Components/Maincomponents/Slidecomponent/Slide.scss
- src/pages/Main/Components/Order/Order.jsx
- src/pages/Main/Components/Order/Order.scss
- src/pages/Main/Components/Product/components/ProductCompo/ProductCompo.jsx
- src/pages/Main/Components/Product/components/ProductDetail/ProductDetail.jsx
- src/pages/Main/Components/Product/components/ProductDetail/ProductDetail.scss
- src/pages/Main/Components/Product/components/ProductDetail/productDetailBottom/ProductDetailBottom.jsx
- src/pages/Main/Components/Product/components/ProductList/ProductList.jsx
- src/pages/Main/Components/Product/components/ProductListItem/PoductListItem/ProductListItem.scss
- src/pages/Main/Components/Product/components/ProductListItem/PoductListItem/productListImg/ProductListImg.jsx
- src/pages/Main/Components/Product/components/ProductListItem/PoductListItem/productListImg/ProductListImg.scss
- src/pages/Main/Components/Recipe/Recipe.jsx
- src/pages/Main/Components/Recipe/RecipePresent.jsx
- src/pages/SignUp/SignUp.jsx
> [41기 권나현] Modify: api 경로 수정 - Feature/last

- src/pages/Main/Components/Cart/Cart.jsx
- src/pages/Main/Components/Cart/Cart.scss
- src/pages/Main/Components/payment/Payment.jsx
> [41기 권나현]Modify: cart POSTapi구현

- src/components/Best/Best.jsx
- src/components/Nav/Nav.jsx
- src/pages/Login/Login.jsx
- src/pages/Main/Components/Cart/Cart.jsx
- src/pages/Main/Components/Maincomponents/Mainbest/BestMenu.jsx
- src/pages/Main/Components/Order/Order.jsx
- src/pages/Main/Components/Product/components/ProductCompo/ProductCompo.jsx
- src/pages/Main/Components/Product/components/ProductDetail/ProductDetail.jsx
- src/pages/Main/Components/Recipe/Recipe.jsx
- src/pages/Main/Components/Recipe/RecipePresent.jsx
- src/pages/Main/Components/payment/OrderPayment.jsx
- src/pages/Main/Components/search/Search.jsx
- src/pages/SignUp/SignUp.jsx
> Modify: fetch url 수정

- src/components/Nav/Nav.jsx
> Modify: 로그아웃 수정

- src/components/Nav/Nav.jsx
> Modify:로그아웃수정

- src/components/Nav/Nav.jsx
Reverts wecode-bootcamp-korea/41-1st-Dwae-Getarian-frontend#48
> Revert "Modify:로그아웃수정"

- src/components/Nav/Nav.jsx
> modify: logoutfixed

- src/pages/Main/Components/Cart/Cart.jsx
- src/pages/Main/Components/Maincomponents/Recipe/Recipe.jsx
- src/pages/Main/Components/Order/Order.jsx
- src/pages/Main/Components/Product/components/ProductDetail/ProductDetail.jsx
> [41기 조윤환]Modify: 수정

- src/Router.js
> [41기 정다경] modifyLogin2

- src/components/Best/Best.jsx
- src/pages/Main/Components/Cart/Cart.jsx
- src/pages/Main/Components/Order/Order.jsx
- src/pages/Main/Components/Product/components/ProductCompo/ProductCompo.jsx
- src/pages/Main/Components/Product/components/ProductDetail/ProductDetail.jsx
- src/pages/Main/Components/Product/components/ProductList/ProductList.jsx
- src/pages/Main/Components/Product/components/ProductNav/ProductNav.jsx
> [41기 권나현]Feature/last

- src/pages/Main/Components/Product/components/ProductDetail/ProductDetail.scss
- src/pages/Main/Components/Product/components/ProductListItem/PoductListItem/productListImg/ProductListImg.scss
> Modify: 이미지 변경
